### ISSUE TITLE
removing dependencies

### ISSUE THREAD

**Issue by yawetse** [bergloman/JsGridSearch#1]
Hey is it possible to remove `colors` as a dependency since it's not being used.

**Comment by bergloman** [comment]
Hello
Actually, `colors` module is being used - the dependency just isn't visible. I will change the way it is being used, so the it is clear where we need it.
Thank you for pointing this out.

**Comment by bergloman** [comment]
@yawetse - one more thing.
Yesterday, you published a package to npm.org:

https://www.npmjs.com/package/parameter-tuning

It is built from this github repo:

https://github.com/repetere/parameter-tuning

This code is stolen from my repository - nowhere do you acknowledge original author, you changed the licence, but all the code is the same. You tried to remove the colors module and it didn't work.

Stop doing that, instead start giving back to community, from where you take a lot of stuff.

**Comment by yawetse** [comment]
@bergloman I'm happy to unpublished it, I just wanted a module with no dependencies, and I love what you've done with grid search!

Is it possible to publish a version without colors?

**Comment by bergloman** [comment]
Yes, it is.
I will do it soon.

**Comment by bergloman** [comment]
It is available here:
https://www.npmjs.com/package/js-grid-search-lite

**Comment by yawetse** [comment]
@bergloman perfect! Thanks! I appreciate the quick response
